/**
 * Single commit row UI, render only, no business logic
 * Columns are conditionally rendered based on ColumnFlags; grid-template-columns are generated by the parent
 */
import type { MouseEvent } from 'react';
import type { Commit } from '../../../shared/domain';
import type { GraphRow } from '../utils/commitGraph';
import { relativeTime, firstLine, shortHash } from '../utils/formatters';
import { CommitGraph } from './CommitGraph';
import type { ColumnFlags } from './CommitList';

interface Props {
  commit: Commit;
  columns: ColumnFlags;
  graphRow: GraphRow;
  maxLanes: number;
  selected: boolean;
  onClick: (item: string, event: MouseEvent) => void;
  onContextMenu: (item: string, event: MouseEvent) => void;
}

export function CommitItem({
  commit,
  columns,
  graphRow,
  maxLanes,
  selected,
  onClick,
  onContextMenu,
}: Props) {
  return (
    <div
      className={`commit-item${selected ? ' is-selected' : ''}`}
      onClick={(e) => onClick(commit.hash, e)}
      onContextMenu={(e) => {
        e.preventDefault();
        onContextMenu(commit.hash, e);
      }}
      title={commit.message}
    >
      {columns.graph && (
        <CommitGraph
          row={graphRow}
          maxLanes={maxLanes}
          isUnpushed={commit.isUnpushed}
        />
      )}
      <span className="commit-message">{firstLine(commit.message)}</span>
      {columns.author && <span className="commit-author">{commit.author}</span>}
      {columns.hash && <span className="commit-hash">{shortHash(commit.hash)}</span>}
      {columns.time && <span className="commit-time">{relativeTime(commit.date)}</span>}
      {columns.tags && commit.refs.length > 0 && (
        <span className="commit-tags">
          {commit.refs.map((ref) => (
            <span
              key={ref}
              className={`commit-tag${commit.isUnpushed ? ' is-unpushed' : ''}`}
            >
              {ref}
            </span>
          ))}
        </span>
      )}
    </div>
  );
}
